export const METADATA_CONSTANTS = {
  CONFIDENCE_MIN: 0,
  CONFIDENCE_MAX: 1,
  CONFIDENCE_DEFAULT: 0.5,
  CONFIDENCE_VERIFIED: 1.0,
  DEFAULT_PAGE_SIZE: 50,
  MAX_PAGE_SIZE: 1000
} as const;

export const DEFAULT_SOURCE_PRIORITIES = {
  USER_EDIT: 100,
  LOCAL_TAGS: 80,
  PLUGIN: 60,
  MUSICBRAINZ: 50,
  DISCOGS: 45,
  SPOTIFY: 40,
  LASTFM: 30,
  AI: 20
} as const;
