import { eq, sql, asc } from 'drizzle-orm';

import { createCollectionId } from '../../../../../src/common/collections/id';
import { PlaylistEngine } from '../../../../../src/main/collections/engine/PlaylistEngine';
import { UndoEngine } from '../../../../../src/main/collections/engine/UndoEngine';
import { MembershipCache } from '../../../../../src/main/collections/membership/MembershipCache';
import { MembershipService } from '../../../../../src/main/collections/membership/MembershipService';
import { AddSongsOp } from '../../../../../src/main/collections/operations/AddSongsOp';
import { DeleteOp } from '../../../../../src/main/collections/operations/DeleteOp';
import { OperationExecutor } from '../../../../../src/main/collections/operations/OperationExecutor';
import { OperationJournalWriter } from '../../../../../src/main/collections/operations/OperationJournalWriter';
import { OperationRegistry } from '../../../../../src/main/collections/operations/OperationRegistry';
import { RemoveSongsOp } from '../../../../../src/main/collections/operations/RemoveSongsOp';
import { RenameOp } from '../../../../../src/main/collections/operations/RenameOp';
import { ReorderOp } from '../../../../../src/main/collections/operations/ReorderOp';
import { RestorePlaylistOp } from '../../../../../src/main/collections/operations/RestorePlaylistOp';
import { RestoreSongsOp } from '../../../../../src/main/collections/operations/RestoreSongsOp';
import { OperationJournalRepository } from '../../../../../src/main/collections/repositories/OperationJournalRepository';
import { PlaylistRepository } from '../../../../../src/main/collections/repositories/PlaylistRepository';
import { db } from '../../../../../src/main/db/db';
import {
  playlists,
  playlistEntries,
  songs,
  operationJournal
} from '../../../../../src/main/db/schema';

describe('UndoEngine', () => {
  let repository: PlaylistRepository;
  let journalWriter: OperationJournalWriter;
  let executor: OperationExecutor;
  let registry: OperationRegistry;
  let journalRepo: OperationJournalRepository;
  let membershipService: MembershipService;

  let playlistEngine: PlaylistEngine;
  let undoEngine: UndoEngine;

  let testPlaylistId: number;
  let testSongIds: number[];

  beforeEach(async () => {
    // Clear DB
    await db.delete(operationJournal);
    await db.delete(playlistEntries);
    await db.delete(playlists);
    await db.delete(songs);

    // SQLite rowid tables accept explicit id inserts; the PG build needed
    // `ALTER COLUMN id SET GENERATED BY DEFAULT` here (no-op on SQLite)

    // Initialize dependencies
    repository = new PlaylistRepository();
    journalWriter = new OperationJournalWriter();
    executor = new OperationExecutor(journalWriter);
    registry = new OperationRegistry();
    journalRepo = new OperationJournalRepository();
    membershipService = new MembershipService(new MembershipCache(), []);

    // Register all operations in registry
    registry.register('playlist.addSongs', new AddSongsOp(repository));
    registry.register('playlist.removeSongs', new RemoveSongsOp(repository));
    registry.register('playlist.rename', new RenameOp(repository));
    registry.register('playlist.reorder', new ReorderOp(repository));
    registry.register('playlist.delete', new DeleteOp(repository));
    registry.register('playlist.restoreSongs', new RestoreSongsOp(repository));
    registry.register('playlist.restore', new RestorePlaylistOp(repository));

    undoEngine = new UndoEngine(registry, journalRepo, executor, membershipService);
    playlistEngine = new PlaylistEngine(repository, membershipService, executor);

    // Setup initial data
    const [insertedPlaylist] = await db
      .insert(playlists)
      .values({
        name: 'Test Playlist'
      })
      .returning();
    testPlaylistId = insertedPlaylist.id;

    const now = new Date();
    const insertedSongs = await db
      .insert(songs)
      .values([
        {
          title: 'Song 1',
          artist: 'Artist 1',
          album: 'Album 1',
          path: '/1.mp3',
          duration: 100,
          fileCreatedAt: now,
          fileModifiedAt: now
        },
        {
          title: 'Song 2',
          artist: 'Artist 2',
          album: 'Album 2',
          path: '/2.mp3',
          duration: 120,
          fileCreatedAt: now,
          fileModifiedAt: now
        },
        {
          title: 'Song 3',
          artist: 'Artist 3',
          album: 'Album 3',
          path: '/3.mp3',
          duration: 140,
          fileCreatedAt: now,
          fileModifiedAt: now
        }
      ])
      .returning();
    testSongIds = insertedSongs.map((s) => s.id);
  });

  afterEach(async () => {
    await db.delete(operationJournal);
    await db.delete(playlistEntries);
    await db.delete(playlists);
    await db.delete(songs);
  });

  const getCollectionId = () => createCollectionId('local', 'playlist', testPlaylistId);

  it('should undo and redo addSongs', async () => {
    await playlistEngine.addSongs({
      playlistId: testPlaylistId,
      songIds: [testSongIds[0], testSongIds[1]]
    });

    let entries = await repository.getEntries(testPlaylistId);
    expect(entries.length).toBe(2);

    const undone = await undoEngine.undo(getCollectionId());
    expect(undone).toBe(true);

    entries = await repository.getEntries(testPlaylistId);
    expect(entries.length).toBe(0);

    const redone = await undoEngine.redo(getCollectionId());
    expect(redone).toBe(true);

    entries = await repository.getEntries(testPlaylistId);
    expect(entries.length).toBe(2);
  });

  it('should discard redo branch on new operation', async () => {
    await playlistEngine.addSongs({ playlistId: testPlaylistId, songIds: [testSongIds[0]] }); // Seq 1
    await playlistEngine.renamePlaylist({ playlistId: testPlaylistId, newName: 'Renamed' }); // Seq 2

    // Undo rename
    await undoEngine.undo(getCollectionId());
    let p = await repository.getById(testPlaylistId);
    expect(p?.name).toBe('Test Playlist');

    // New operation -> discards redo
    await playlistEngine.addSongs({ playlistId: testPlaylistId, songIds: [testSongIds[1]] }); // Seq 3

    // Attempt redo, should fail
    const redone = await undoEngine.redo(getCollectionId());
    expect(redone).toBe(false); // Because redo stack was cleared

    p = await repository.getById(testPlaylistId);
    expect(p?.name).toBe('Test Playlist'); // Did not revert to 'Renamed'
  });

  it('should not change in-memory pointer or journal on transaction rollback', async () => {
    await playlistEngine.addSongs({ playlistId: testPlaylistId, songIds: [testSongIds[0]] });

    // Let's break the registry so that undo throws an error
    const originalGet = registry.get.bind(registry);
    registry.get = () => {
      throw new Error('Simulated failure during undo');
    };

    const initialJournalCount = (await db.select().from(operationJournal)).length;
    expect(initialJournalCount).toBe(1);

    await expect(undoEngine.undo(getCollectionId())).rejects.toThrow(
      'Simulated failure during undo'
    );

    // Restore registry
    registry.get = originalGet;

    // Verify pointer was not changed (we can still undo successfully now)
    const journalCountAfter = (await db.select().from(operationJournal)).length;
    expect(journalCountAfter).toBe(1); // Journal unchanged

    // We can still undo because the pointer is still pointing to the last item
    const success = await undoEngine.undo(getCollectionId());
    expect(success).toBe(true);

    const entries = await repository.getEntries(testPlaylistId);
    expect(entries.length).toBe(0);
  });

  it('should support multi-step undo and redo chain', async () => {
    // 1. Add songs
    await playlistEngine.addSongs({
      playlistId: testPlaylistId,
      songIds: [testSongIds[0], testSongIds[1]]
    });
    let entries = await db
      .select()
      .from(playlistEntries)
      .where(eq(playlistEntries.playlistId, testPlaylistId))
      .orderBy(asc(playlistEntries.position));
    const entryIdToReorder = entries[0].id;

    // 2. Rename playlist
    await playlistEngine.renamePlaylist({
      playlistId: testPlaylistId,
      newName: 'Renamed Playlist'
    });

    // 3. Reorder songs
    await playlistEngine.reorderSongs({
      playlistId: testPlaylistId,
      entryId: entryIdToReorder,
      newPosition: 1
    });

    // Verify state after 3 steps
    let p = await db.query.playlists.findFirst({ where: eq(playlists.id, testPlaylistId) });
    expect(p?.name).toBe('Renamed Playlist');
    entries = await db
      .select()
      .from(playlistEntries)
      .where(eq(playlistEntries.playlistId, testPlaylistId))
      .orderBy(asc(playlistEntries.position));
    expect(entries[1].songId).toBe(testSongIds[0]); // was reordered

    const cid = getCollectionId();

    // Undo 3: Reorder
    await undoEngine.undo(cid);
    entries = await db
      .select()
      .from(playlistEntries)
      .where(eq(playlistEntries.playlistId, testPlaylistId))
      .orderBy(asc(playlistEntries.position));
    expect(entries[0].songId).toBe(testSongIds[0]); // reorder reverted

    // Undo 2: Rename
    await undoEngine.undo(cid);
    p = await db.query.playlists.findFirst({ where: eq(playlists.id, testPlaylistId) });
    expect(p?.name).toBe('Test Playlist'); // rename reverted

    // Redo 2: Rename
    await undoEngine.redo(cid);
    p = await db.query.playlists.findFirst({ where: eq(playlists.id, testPlaylistId) });
    expect(p?.name).toBe('Renamed Playlist'); // renamed again

    // Redo 3: Reorder
    await undoEngine.redo(cid);
    entries = await db
      .select()
      .from(playlistEntries)
      .where(eq(playlistEntries.playlistId, testPlaylistId))
      .orderBy(asc(playlistEntries.position));
    expect(entries[1].songId).toBe(testSongIds[0]); // reordered again

    // Undo 3, Undo 2, Undo 1
    await undoEngine.undo(cid); // Undo Reorder
    await undoEngine.undo(cid); // Undo Rename
    await undoEngine.undo(cid); // Undo Add

    entries = await db
      .select()
      .from(playlistEntries)
      .where(eq(playlistEntries.playlistId, testPlaylistId))
      .orderBy(asc(playlistEntries.position));
    expect(entries.length).toBe(0); // All gone
  });

  it('should fully restore a deleted playlist (Undo DeleteOp)', async () => {
    await playlistEngine.addSongs({ playlistId: testPlaylistId, songIds: testSongIds });

    // Delete playlist
    await playlistEngine.deletePlaylist({ playlistId: testPlaylistId });

    let p = await repository.getById(testPlaylistId);
    expect(p).toBeNull();
    let entries = await repository.getEntries(testPlaylistId);
    expect(entries.length).toBe(0);

    // Undo Delete
    const undone = await undoEngine.undo(getCollectionId());
    expect(undone).toBe(true);

    p = await repository.getById(testPlaylistId);
    expect(p).not.toBeNull();
    expect(p?.name).toBe('Test Playlist');

    entries = await repository.getEntries(testPlaylistId);
    expect(entries.length).toBe(3);
  });
});
